version: '3.9'

volumes:
  postgres-data:
    driver: local
  kafka-data:
    driver: local

services:
  dispatcher:
    container_name: dispatcher
    restart: on-failure
    build:
      context: ./
      dockerfile: ./dispatcher/Dockerfile
    ports:
      - ${DISPATCHER_PORT}:${DISPATCHER_PORT}
    environment:
      DISPATCHER_PORT: ${DISPATCHER_PORT}
      BOT_URI: ${BOT_URI}
      BOT_USERNAME: ${BOT_USERNAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      ANSWER_TOPIC: ${ANSWER_TOPIC}
      EDIT_TOPIC: ${EDIT_TOPIC}
      TEXT_UPDATE_TOPIC: ${TEXT_UPDATE_TOPIC}
      CALLBACK_QUERY_UPDATE_TOPIC: ${CALLBACK_QUERY_UPDATE_TOPIC}
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    depends_on:
      kafka:
        condition: service_healthy

  node:
    container_name: node
    restart: on-failure
    build:
      context: ./
      dockerfile: ./node/Dockerfile
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    environment:
      NODE_PORT: ${NODE_PORT}
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      ANSWER_TOPIC: ${ANSWER_TOPIC}
      EDIT_TOPIC: ${EDIT_TOPIC}
      TEXT_UPDATE_TOPIC: ${TEXT_UPDATE_TOPIC}
      CALLBACK_QUERY_UPDATE_TOPIC: ${CALLBACK_QUERY_UPDATE_TOPIC}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HH_USER_AGENT: ${HH_USER_AGENT}
      HH_SEARCH_FOR_VACANCY: ${HH_SEARCH_FOR_VACANCY}
      NOTIFIER_PERIOD: ${NOTIFIER_PERIOD}
      AREA_PERIOD: ${AREA_PERIOD}
      SALT: ${SALT}
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy

  kafka:
    container_name: kafka
    hostname: kafka
    image: apache/kafka:3.7.1
    ports:
      - ${KAFKA_PORT_MAPPING}
    volumes:
      - kafka-data:/var/lib/kafka
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 30s
    restart: unless-stopped

  postgres:
    container_name: postgres-db
    image: postgres:14.5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_MAPPING}
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE} -h 127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped


