server:
  port: ${NODE_PORT:8091}

spring:
  cache:
    type: redis
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    redis:
      time-to-live: -1
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:29092}
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/hhb_db}
    username: ${POSTGRES_USERNAME:getname}
    password: ${POSTGRES_PASSWORD:4002}
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
  liquibase:
    enabled: true

topics:
  answer-topic: ${ANSWER_TOPIC:answer}
  edit-topic: ${EDIT_TOPIC:edit}
  text-update-topic: ${TEXT_UPDATE_TOPIC:text-update}
  callback-query-update-topic: ${CALLBACK_QUERY_UPDATE_TOPIC:callback-update}

headhunter:
  count-vacancies-in-page: 100
  period-of-days: 2
  vacancies-get-url: ${HH_SEARCH_FOR_VACANCY:https://api.hh.ru/vacancies}
  area-get-url: https://api.hh.ru/areas

notifier:
  period: ${NOTIFIER_PERIOD:3600000}

area:
  update-period: ${AREA_PERIOD:864000000}

salt: ${SALT:qwertyuiiuytrewer}

admin:
  password: ${ADMIN_PASSWORD:1234}

logging:
  config: classpath:log4j2.xml





