CREATE TABLE hhbot.t_config
(
    config_id         bigint generated by default as identity
        constraint app_user_config_pkey
            primary key,
    config_name            varchar(255),
    experience             varchar(255),
    last_notification_time timestamp(6),
    query_text             varchar(255),
    area                   varchar(255),
    app_user_id            bigint
        constraint fk_app_user_config
            references hhbot.t_app_user
);