CREATE TABLE hhbot.t_app_user
(
    user_id          bigint generated by default as identity
        constraint app_user_pkey
            primary key,
    first_login_date timestamp(6),
    first_name       varchar(255),
    last_name        varchar(255),
    telegram_id      bigint                                        not null
        constraint app_user_telegram_id_key
            unique,
    username         varchar(255),
    role             varchar(32) default 'USER'::character varying not null
);