databaseChangeLog:
  - changeSet:
      id: 3
      author: getname
      changes:
        - createTable:
            tableName: app_user_config
            columns:
              - column:
                  name: user_config_id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: config_name
                  type: varchar(255)
              - column:
                  name: education_params
                  type: education_param[]
              - column:
                  name: experience
                  type: varchar(255)
                  constraints:
                    checkConstraint: experience::text = ANY (ARRAY['NO_MATTER', 'NO_EXPERIENCE', 'BETWEEN_1_AND_3', 'BETWEEN_3_AND_6', 'MORE_THEN_6']::text[])
              - column:
                  name: last_notification_time
                  type: timestamp(6)
              - column:
                  name: query_text
                  type: varchar(255)
              - column:
                  name: region
                  type: varchar(255)
              - column:
                  name: schedule_params
                  type: schedule_param[]
              - column:
                  name: app_user_id
                  type: bigint
                  constraints:
                    foreignKeyName: fk_app_user_config_app_user
                    references: app_user(user_id)
