package com.bipbup.enums;

public enum AppUserState {
    BASIC_STATE,
    WAIT_CONFIG_NAME_STATE,
    WAIT_QUERY_STATE,
    QUERY_LIST_STATE,
    QUERY_MENU_STATE,
    QUERY_DELETE_STATE,
    QUERY_UPDATE_STATE,
    WAIT_AREA_STATE,
    WAIT_EXPERIENCE_STATE,
    WAIT_EDUCATION_STATE,
    WAIT_SCHEDULE_STATE
}
